apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: techdeepa20/nginx:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets: 
      - name: demo